version: '3.8'

services:
  mysql:
    build: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: Cinema
      MYSQL_USER: user
      MYSQL_PASSWORD: pw
    volumes:
      - mysql-data:/var/lib/mysql                 # Persistência dos dados
      - ./Cinema.sql:/docker-entrypoint-initdb.d  # Arquivos de inicialização
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p12345678"] #Verifica se o mysql esta a funcionar , define o host como local host
      interval: 10s # a cada 10 seg verifica o status do my sql
      timeout: 5s #define o tempo maximo para responder antes de considerar erro 
      retries: 5 # Numero de tentivar para testar
      start_period: 15s # define o periodo para validar que nao houve falhas

  nodejs:
    build: nodejs-Cinema
    environment:
      DATABASE_HOST: mysql
      DATABASE_PORT: 3306
      DATABASE_NAME: Cinema
      DATABASE_USER: root
      DATABASE_PASSWORD: 12345678
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    command: 
      "npm start"

volumes:
  mysql-data:
    driver: local
